import Wrapper from "./Wrapper";
import StyledComponentsRegistry from "./registry.js";

export const metadata = {
  title: "Foodie Fusion",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/x-icon" href="/images/favicon.ico" />
        <script src="//cdn.jsdelivr.net/npm/eruda"></script>
        <script>eruda.init();</script>
      </head>
      <body>
        <StyledComponentsRegistry>
          <Wrapper>{children}</Wrapper>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
